pipeline:
  name: python-pipeline-sample
  identifier: pythonpipelinesample
  projectIdentifier: pythonpipelinesample
  orgIdentifier: WiproPOC
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GenericGit
        timeout: 20m
        repoName: python-pipeline-samples
        build: <+input>
  stages:
    - stage:
        name: build test and docker
        identifier: build_test_and_docker
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8sDeligate
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: compile
                  identifier: compile
                  spec:
                    connectorRef: dockerdeepak
                    image: python:3.10.6-alpine
                    shell: Sh
                    command: python -m compileall ./
                    privileged: false
              - step:
                  type: Run
                  name: createDockerfile
                  identifier: createDockerfile
                  spec:
                    connectorRef: dockerdeepak
                    image: alpine
                    shell: Sh
                    command: |-
                      touch pythondockerfile
                      cat > pythondockerfile <<- EOM
                      FROM python:3.10.6-alpine
                      WORKDIR /python-pipeline-samples
                      ADD . /python-pipeline-samples
                      RUN pip install -r requirements.txt
                      CMD ["python" , "app.py"]
                      EOM
                      cat pythondockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build and push docker image
                  identifier: build_and_push_docker_image
                  spec:
                    connectorRef: dockerdeepak
                    repo: dockerdeepak/harness-py-sample
                    tags:
                      - latest
                      - v1
                    dockerfile: pythondockerfile
          caching:
            enabled: false
            paths: []
