pipeline:
  name: python-sample
  identifier: pythonsample
  projectIdentifier: pythonsample
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pythonsample
        build: <+input>
  stages:
    - stage:
        name: build Test and Deploy
        identifier: build_Test_and_Deploy
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: python compile
                  identifier: python_compile
                  spec:
                    connectorRef: dockerhub
                    image: python:3.10.6-alpine
                    shell: Sh
                    command: python -m compileall ./
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
